name: 'Body Elite Fitness '
favicon: null
layout_spectrum: 0.10234661982394755
typography_spectrum: 0.21501387632451952
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9354453017003834
  lightness: 0.3562203210312873
  saturation: 0.4036678597331047
  rhythmicContrast: 0.10552541562356055
purpose: []
